name: Build, Scan and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: |
            vulnerable-app:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/vulnerable-app:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/vulnerable-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: vulnerable-app:${{ github.sha }}
          args: --file=Dockerfile --severity-threshold=high  --json-file-output=snyk-results.json
        continue-on-error: true
        
      - name: Upload Snyk results
        uses: actions/upload-artifact@v4
        with:
          name: snyk-scan-results
          path: snyk-results.json
        if: always()

      - name: Monitor Docker image in Snyk
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: vulnerable-app:${{ github.sha }}
          command: monitor
          args: --file=Dockerfile
          
      - name: Push Docker image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vulnerable-app:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/vulnerable-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
