name: Snyk Container Scan

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  snyk-container-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t vulnerable-app:${{ github.sha }} .

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: vulnerable-app:${{ github.sha }}
          args: --file=Dockerfile --severity-threshold=high
        continue-on-error: true

      - name: Print Snyk scan results
        run: |
          echo "Snyk Container Scan Results:"
          snyk container test vulnerable-app:${{ github.sha }} --json | tee snyk-results.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
        
      - name: Monitor Docker image in Snyk
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: vulnerable-app:${{ github.sha }}
          command: monitor
          args: --file=Dockerfile

      - name: Upload Snyk scan results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
        if: always()
